### ISSUE TITLE
Halo Keyboard different layout

### ISSUE THREAD

**Issue by Txori** [jekhor/yogabook-linux#23]
Hi. My ENTER key was acting weird, so I discovered that I don't have the same keyboard layout. It's a QWERTY keyboard, but slightly different:

![yogabook_kb_layout](https://user-images.githubusercontent.com/3765943/121345636-662b0380-c925-11eb-88b4-88d0b59f14dd.png)

I wrote a script to convert etc/touch_keyboard/layout.csv to a SVG file in order to see what's going on:
https://www.w3schools.com/code/tryit.asp?filename=GRC9DDYNX1SH

Now I'm going to modify it. Do I have to modify other files in your ubuntu-yb/rootfs folder in order to make it work?
I'll send the final file when it will be done. Do you happen to know the technical version number or country code of that keyboard layout?

Thanks

**Comment by jekhor** [comment]
Hi.
The latest touchkeyboard support package has support for different layouts
already.  I will explain how to use them late here if I will have enough
time.

ср, 9 чэр 2021, 14.25 карыстальнік Txori ***@***.***> напісаў:

**Comment by Txori** [comment]
Oh, all right. Thank you :)

**Comment by Txori** [comment]
By the way, I was wondering, how halo keyboard works on Linux... Is it a simple driver, or does it need special things in the kernel?
I'm currently running Xubuntu on my Yoga Book. How hard would it be to use that keyboard driver on some other OS, like ChromeOS or other Linux distro?

**Comment by TiNredmc** [comment]
@Txori the way that it works is similar to windows, exception that Linux sees that touch keyboard as a touchscreen (technically it is) but @jekhor wrote the hwdb file to config libinput to ignore the touch input not to use it as touchscreen. He also wrote special program to read "event" from input ("event" in this case is the x,y coordinate when finger(s) touch the surface) and emulate itself as a virtual keyboard and mouse. That program is called Keyboard handler.

On the other hand on Windows, The driver is specially written. The keyboard handler is built-into the Goodix touchscreen driver, that have access to Intel's PWM api, thus you can change keyboard brightness. But the haptic feedback is different part, they have their own program to handle the haptic feedback when button is pressed by user.

About using touch keyboard on chromeOS is possible. But there're 3 things to concern.

1. Since ChromeOS is Linux, It can run normal linux binary (program). But his keyboard handler require the hardware access which can be different between chromeOS and other Debian-Based linux. 
2. The way to make the keyboard works is also rely on "udev", afaik is the somthings likes hardware management software, It helps loading driver or run automated script when event happen (hardware detected, removed, etc). But on ChromeOS, I don't think they use udev.
3. Driver on ChromeOS kernel isn't exactly from official (Mainline) Linux kernel, so to get the Yoga up and runnung. All sort of device drivers including Goodix touch keyboard driver need to be ported over to ChromeOS.

And by the way, ChromeOS is (technically) only available on commercial device. But you rather use ChromiumOS that actually open source.

**Comment by jekhor** [comment]
> By the way, I was wondering, how halo keyboard works on Linux... Is it a simple driver, or does it need special things in the kernel?
> I'm currently running Xubuntu on my Yoga Book. How hard would it be to use that keyboard driver on some other OS, like ChromeOS or other Linux distro?

I use special userspace driver ported from experimental ChromeOS driver. Original driver never had been in production and was removed from ChromeOS some time ago.

**Comment by jekhor** [comment]
> Oh, all right. Thank you :)

The manual which I promised:
# Install the latest touch-keyboard package from https://github.com/jekhor/chromiumos_touch_keyboard/releases/tag/1.4.1
# Go to /etc/touch_keyboard/layouts/
# Remove existing layout.csv symlink
# make new symlink to your variant: `ln -s YB1-X9x-pc104.csv layout.csv`

**Comment by jekhor** [comment]
I re-checked, your variant is PC-105 and it is used by default in the touch-keyboard 1.4.1 package.

**Comment by Txori** [comment]
Thanks, I saw that. It was working nicely on Xubuntu following your manual, but since then, I formatted to Neverware's CloudReady and didn't start playing with chromiumos_touch_keyboard yet. I think I'll try with FydeOS too.

**Comment by RiccardoPP** [comment]
I have an issue with this. My `/etc/touch_keyboard/layout.csv` is from the PC-105 variant, but I continue to see the PC-104 variant on Halo Keyboard. I'm on Arch Linux with the latest touch-keyboard package (1.4.2-1). Any suggestion? Keyboard and touchpad are working fine.

Thanks.

**Comment by DerKnerd** [comment]
@RiccardoPP the keyboard and touchpad are actually etched into the glass. It is not a display.

**Comment by RiccardoPP** [comment]
> [@RiccardoPP](https://github.com/RiccardoPP) the keyboard and touchpad are actually etched into the glass. It is not a display.


Ahhh, ok, ok. Thank you.
